#!/bin/bash -e

recreate_files()
{
	rm -rf files
	mkdir files
	mkdir files/A
	touch files/A/x
	touch files/A/y
	ln -s ../B/B files/A/B
	#ln -s ../B/nonexistent files/A/dangling # TODO
	mkdir files/B
	touch files/B/x
	touch files/B/y
	ln -s ../A/x files/B/ax
	ln -s ../A files/B/A
	mkdir files/B/B
	touch files/B/B/x
	touch files/B/B/y
	ln -s ../../A files/B/B/A
}

show_files()
{
	find files -printf '%U %G %p\n' | sort -k4
}

for script in /proj/tests/chown_tests/*.run; do
	echo "chown: Running $script"
	expected_output=${script//.run/.out}
	expected_attribs=${script//.run/.attribs}
	recreate_files
	#$script >$expected_output || ret=$?
	$script >/tmp/test_output || ret=$?
	if (( ret != 0 )); then
		echo "chown: FAIL $script exited with code $ret" >&2
		exit 1
	fi
	#show_files >$expected_attribs
	show_files >/tmp/test_attribs
	if ! cmp -s $expected_output /tmp/test_output; then
		echo "chown: FAIL $script output does not match expected output" >&2
		diff -u $expected_output /tmp/test_output
		exit 1
	fi
	if ! cmp -s $expected_attribs /tmp/test_attribs; then
		echo "chown: FAIL $script result attributes do not match expected attributes" >&2
		diff -u $expected_attribs /tmp/test_attribs
		exit 1
	fi
	echo "chown: OK"
done
